# Basic Python

## 1. Split this string

In [4]:
s = "Hi there Sam!"

In [5]:
str.split(s)

['Hi', 'there', 'Sam!']

## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [6]:
planet = "Earth"
diameter = 12742

In [10]:
s="the diameter of {} is {} kilometers"
print(s.format(planet,diameter))

the diameter of Earth is 12742 kilometers


## 3. In this nest dictionary grab the word "hello"

In [11]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [12]:
d['k1'][3]['tricky'][3]['target'][3]

'hello'

# Numpy

In [13]:
import numpy as np

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [14]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [16]:
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

## 5. Create an array of all the even integers from 20 to 35

In [17]:
np.arange(20,35,2)

array([20, 22, 24, 26, 28, 30, 32, 34])

## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [21]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

## 7. Concatenate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [23]:
a=np.array([1,2,3])
b=np.array([4,5,6])
print(np.concatenate((a,b),axis=None))

[1 2 3 4 5 6]


# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [24]:
import pandas as pd


In [44]:
data = [[15,'ravi' ], [13,'mani'], [14, 'ram']]
df = pd.DataFrame(data, columns=['rollno', 'student'])
print(df)

   rollno student
0      15    ravi
1      13    mani
2      14     ram


## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [34]:
from datetime import timedelta,date
def daterange(date1,date2):
    for n in range (int((date2-date1).days)+1):
        yield date1+timedelta(n)
start_dt=date(2023,1,1)
end_dt=date(2023,2,10)
for dt in daterange(start_dt, end_dt):
    print(dt.strftime("%y-%m-%d"))
            

23-01-01
23-01-02
23-01-03
23-01-04
23-01-05
23-01-06
23-01-07
23-01-08
23-01-09
23-01-10
23-01-11
23-01-12
23-01-13
23-01-14
23-01-15
23-01-16
23-01-17
23-01-18
23-01-19
23-01-20
23-01-21
23-01-22
23-01-23
23-01-24
23-01-25
23-01-26
23-01-27
23-01-28
23-01-29
23-01-30
23-01-31
23-02-01
23-02-02
23-02-03
23-02-04
23-02-05
23-02-06
23-02-07
23-02-08
23-02-09
23-02-10


## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [40]:
import pandas as pd

In [42]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]
df=pd.DataFrame(lists)
print(df)

   0    1   2
0  1  aaa  22
1  2  bbb  25
2  3  ccc  24
